version: "3.9"
services:
  pg_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - data
    ports:
      - "5432:5432"
  dj_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg_db
    restart: always
    volumes:
      - ./webpython:/app
    env_file:
      - ./config/.env
    networks:
      - data
      - backend
    expose:
      - 8080

  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./webpython:/app
      - ./config/proxy_params.conf:/etc/nginx/proxy_params
    depends_on:
      - dj_app

    networks:
      - backend
    ports:
      - 80:80

  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - data
    ports:
      - 8081:80

networks:
  data:
  backend:
